
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS IF INDEX LPAREN LSPAREN MINUS NUMBER PLUS RPAREN RSPAREN SEMICOLON TIMES\n    expression : expression PLUS term\n               | expression MINUS term\n               | term\n    \n    term : term TIMES factor\n         | term DIVIDE factor\n         | factor\n    \n    factor : NUMBER\n           | LPAREN expression RPAREN\n    \n    assignment : INDEX EQUALS expression SEMICOLON\n    \n    if_statement : IF LPAREN expression EQUALS EQUALS NUMBER RPAREN LSPAREN expression RSPAREN\n    '
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-3,-6,-7,-1,-2,-4,-5,-8,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[6,-3,-6,-7,6,-1,-2,-4,-5,-8,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[7,-3,-6,-7,7,-1,-2,-4,-5,-8,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-3,-6,-7,15,-1,-2,-4,-5,-8,]),'TIMES':([2,3,4,11,12,13,14,15,],[8,-6,-7,8,8,-4,-5,-8,]),'DIVIDE':([2,3,4,11,12,13,14,15,],[9,-6,-7,9,9,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression','bonsay_assembly_tool 2.0.py',164),
  ('expression -> expression MINUS term','expression',3,'p_expression','bonsay_assembly_tool 2.0.py',165),
  ('expression -> term','expression',1,'p_expression','bonsay_assembly_tool 2.0.py',166),
  ('term -> term TIMES factor','term',3,'p_term','bonsay_assembly_tool 2.0.py',179),
  ('term -> term DIVIDE factor','term',3,'p_term','bonsay_assembly_tool 2.0.py',180),
  ('term -> factor','term',1,'p_term','bonsay_assembly_tool 2.0.py',181),
  ('factor -> NUMBER','factor',1,'p_factor','bonsay_assembly_tool 2.0.py',193),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','bonsay_assembly_tool 2.0.py',194),
  ('assignment -> INDEX EQUALS expression SEMICOLON','assignment',4,'p_assignment','bonsay_assembly_tool 2.0.py',205),
  ('if_statement -> IF LPAREN expression EQUALS EQUALS NUMBER RPAREN LSPAREN expression RSPAREN','if_statement',10,'p_if_statement','bonsay_assembly_tool 2.0.py',211),
]
